name: rdtest
channels:
  - rdkit
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - boost=1.63.0=py36h415b752_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.10.16=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.9.11=py36_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.17.3=py36hd14ec0e_0
  - numpy-base=1.17.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1d=h7b6447c_3
  - pandas=0.25.2=py36he6710b0_0
  - pcre=8.43=he6710b0_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - rdkit=2017.09.1=py36_1
  - readline=7.0=h7b6447c_5
  - setuptools=41.6.0=py36_0
  - six=1.13.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - click==7.0
    - dash==1.6.0
    - dash-core-components==1.5.0
    - dash-daq==0.2.1
    - dash-html-components==1.0.1
    - dash-renderer==1.2.0
    - dash-table==4.5.0
    - flask==1.1.1
    - flask-compress==1.4.0
    - future==0.18.2
    - itsdangerous==1.1.0
    - jinja2==2.10.3
    - markupsafe==1.1.1
    - plotly==4.3.0
    - retrying==1.3.3
    - werkzeug==0.16.0
prefix: /home/ubuntu/anaconda3/envs/rdtest
