name: rdtest
channels:
  - rdkit
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2019.10.16=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2019.9.11=py36_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.4=233
  - jpeg=9b=he5867d9_2
  - libboost=1.67.0=hebc422b_4
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_0
  - libxml2=2.9.9=hf6e021a_1
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.15=py36h5e564d8_0
  - mkl_random=1.1.0=py36ha771720_0
  - numpy=1.17.3=py36h4174a10_0
  - numpy-base=1.17.3=py36h6575580_0
  - olefile=0.46=py_0
  - openssl=1.0.2t=h1de35cc_1
  - pandas=0.25.2=py36h0a44026_0
  - pcre=8.43=h0a44026_0
  - pillow=6.2.1=py36hb68e598_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h1de35cc_0
  - py-boost=1.67.0=py36h6440ff4_4
  - python=3.6.5=hc167b69_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=7.0=hc1231fa_4
  - setuptools=41.6.0=py36_0
  - six=1.13.0=py36_0
  - sqlite=3.23.1=hf1716c9_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - ncurses=6.0=0
  - rdkit=2019.09.1.0=py36h65625ec_1
  - pip:
    - click==7.0
    - dash==1.6.0
    - dash-core-components==1.5.0
    - dash-daq==0.2.1
    - dash-html-components==1.0.1
    - dash-renderer==1.2.0
    - dash-table==4.5.0
    - flask==1.1.1
    - flask-compress==1.4.0
    - future==0.18.2
    - itsdangerous==1.1.0
    - jinja2==2.10.3
    - markupsafe==1.1.1
    - plotly==4.3.0
    - retrying==1.3.3
    - werkzeug==0.16.0
prefix: /Users/pwalters/anaconda3/envs/rdtest

